from __future__ import annotations

from agentforge.analyzer import ProjectProfile


class ConfigGenerator:
    """从 ProjectProfile 渲染生成 challenge.yaml、benchmark.py、test_suite.py。"""

    def __init__(self, profile: ProjectProfile):
        self.profile = profile

    def generate_challenge_yaml(self) -> str:
        p = self.profile
        run_args_str = " ".join(p.run_args) if p.run_args else ""
        writable_list = "\n".join(f"    - {w}" for w in p.writable)
        readonly_list = "\n".join(f"    - {r}" for r in p.readonly)
        baseline_line = (
            f"    Baseline: {p.baseline_value}"
            if p.baseline_value is not None
            else ""
        )

        return (
            f"challenge:\n"
            f"  name: '{p.description[:60]}'\n"
            f"  description: |\n"
            f"    {p.description}\n"
            f"    Run command: {p.run_command} {run_args_str}\n"
            f"{baseline_line}\n"
            f"target:\n"
            f"  metric: {p.eval_metric}\n"
            f"  value: {p.suggested_target}\n"
            f"  direction: {p.eval_direction}\n"
            f"tests:\n"
            f"  smoke: '{p.python_cmd} test_suite.py'\n"
            f"  full: '{p.python_cmd} test_suite.py'\n"
            f"  benchmark: '{p.python_cmd} benchmark.py'\n"
            f"constraints:\n"
            f"  writable:\n"
            f"{writable_list}\n"
            f"  read_only:\n"
            f"{readonly_list}\n"
        )

    def generate_benchmark_py(self) -> str:
        p = self.profile
        return (
            '#!/usr/bin/env python3\n'
            '"""Auto-generated benchmark by AgentForge."""\n'
            'import json\n'
            'import os\n'
            '\n'
            '# ---- metric extraction (generated by Codex analysis) ----\n'
            f'{p.metric_extraction}\n'
            '# ---- end metric extraction ----\n'
            '\n'
            'os.makedirs("results", exist_ok=True)\n'
            'with open("results/benchmark.json", "w") as f:\n'
            f'    json.dump({{"{p.eval_metric}": round(score, 6)}}, f, indent=2)\n'
            f'print(f"[benchmark] {p.eval_metric}={{score:.6f}}")\n'
        )

    def generate_test_suite_py(self) -> str:
        p = self.profile
        parts = p.run_command.split()
        run_script = parts[-1] if parts else "main.py"

        # 对多行 import_checks 进行缩进处理，使每行都在函数体内
        import_lines = p.import_checks.split("\n")
        indented_imports = "\n    ".join(import_lines)

        return (
            '#!/usr/bin/env python3\n'
            '"""Auto-generated sanity tests by AgentForge."""\n'
            'import os\n'
            'import sys\n'
            '\n'
            '\n'
            'def test_entry_exists():\n'
            f'    assert os.path.exists("{run_script}"), "入口脚本不存在: {run_script}"\n'
            '    return True\n'
            '\n'
            '\n'
            'def test_imports():\n'
            f'    {indented_imports}\n'
            '    return True\n'
            '\n'
            '\n'
            'tests = [test_entry_exists, test_imports]\n'
            'for t in tests:\n'
            '    try:\n'
            '        assert t()\n'
            '    except Exception as e:\n'
            '        print(f"FAIL: {t.__name__}: {e}")\n'
            '        sys.exit(1)\n'
            'print(f"All {len(tests)} tests passed")\n'
        )

    def generate_all(self) -> dict[str, str]:
        return {
            "challenge.yaml": self.generate_challenge_yaml(),
            "benchmark.py": self.generate_benchmark_py(),
            "test_suite.py": self.generate_test_suite_py(),
        }
